name: Deploy FastAPI to Elastic Beanstalk

on:
  push:
    branches:
      - main
      - feature/phase3
  repository_dispatch:
    types: [deploy_backend]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-3
      EB_APP_NAME: smartspeztech
      EB_ENV_NAME: smartspeztech

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Elastic Beanstalk CLI
        run: |
          pip install awsebcli

      - name: Configure Elastic Beanstalk CLI
        run: |
          eb init ${{ env.EB_APP_NAME }} \
            --region ${{ env.AWS_REGION }} \
            --platform "Python 3.8" \
            --verbose

      - name: Check Elastic Beanstalk status
        run: |
          eb use ${{ env.EB_ENV_NAME }}
          STATUS=$(eb status | grep Status | awk '{print $2}')
          if [ "$STATUS" != "Ready" ]; then
            echo "Environment is not ready. Current status: $STATUS"
            exit 1
          fi

      - name: Configure Elastic Beanstalk environment variables
        run: |
          eb setenv OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
                    ENVIRONMENT="production" || { echo 'setenv failed'; exit 1; }

      - name: Wait for environment variables to be applied
        run: |
          sleep 10  # 環境変数が反映されるのを待機

      - name: Deploy to Elastic Beanstalk
        run: |
          eb use ${{ env.EB_ENV_NAME }}
          eb deploy --staged
