name: Deploy FastAPI to Elastic Beanstalk

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [deploy_backend]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-3 # 修正: 正しいリージョンに変更
      EB_APP_NAME: smartspeztech
      EB_ENV_NAME: smartspeztech

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Elastic Beanstalk CLI
        run: |
          pip install awsebcli

      - name: Initialize Elastic Beanstalk
        run: |
          eb init -p python-3.9 ${{ env.EB_APP_NAME }} --region ${{ env.AWS_REGION }}
          eb create ${{ env.EB_ENV_NAME }}

      - name: Deploy to Elastic Beanstalk
        run: |
          eb use ${{ env.EB_ENV_NAME }}
          eb setenv OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"
          eb deploy --staged
